# Generated by Django 4.1 on 2024-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0002_managertbl_password_managertbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='turftbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20, null=True)),
                ('loc', models.CharField(max_length=20, null=True)),
                ('timing', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('services', models.TextField(max_length=60, null=True)),
                ('amenities', models.TextField(max_length=60, null=True)),
            ],
        ),
    ]
