# Generated by Django 4.1 on 2024-01-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0004_alter_turftbl_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('phoneno', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
