# Generated by Django 4.1 on 2024-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0005_usertbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tname', models.CharField(max_length=20, null=True)),
                ('loc', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=20, null=True)),
                ('amenities', models.TextField(max_length=60, null=True)),
                ('services', models.CharField(max_length=60, null=True)),
                ('bookdate', models.DateField(null=True)),
                ('getin', models.TimeField(null=True)),
                ('getout', models.TimeField(null=True)),
                ('items', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='turftbl',
            name='services',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
