# Generated by Django 5.0.1 on 2024-02-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0006_bookingtbl_alter_turftbl_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtbl',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turf_app.usertbl'),
        ),
    ]
