# Generated by Django 5.0.1 on 2024-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0007_bookingtbl_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertbl',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usertbl',
            name='mname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='managertbl',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='managertbl',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usertbl',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='usertbl',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
