# Generated by Django 5.0.1 on 2024-02-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0008_usertbl_lname_usertbl_mname_alter_managertbl_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewrating_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=6, null=True)),
                ('review', models.TextField(max_length=40, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turf_app.usertbl')),
            ],
        ),
    ]
