# Generated by Django 5.0.1 on 2024-02-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0009_reviewrating_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating_tbl',
            old_name='stars',
            new_name='rating',
        ),
    ]
