# Generated by Django 5.0.1 on 2024-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0010_rename_stars_reviewrating_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating_tbl',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewrating_tbl',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewrating_tbl',
            name='reviews',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
