# Generated by Django 5.0.1 on 2024-02-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0011_remove_reviewrating_tbl_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating_tbl',
            name='rating',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
