# Generated by Django 5.0.1 on 2024-02-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0012_reviewrating_tbl_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating_tbl',
            old_name='reviews',
            new_name='review',
        ),
    ]
