# Generated by Django 5.0.1 on 2024-02-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0013_rename_reviews_reviewrating_tbl_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating_tbl',
            old_name='review',
            new_name='reviews',
        ),
    ]
