# Generated by Django 5.0.1 on 2024-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0016_reviewrating_tbl_fname_alter_reviewrating_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating_tbl',
            name='fname',
        ),
    ]
