# Generated by Django 5.0.1 on 2024-02-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0017_remove_reviewrating_tbl_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='turfreview_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=15, null=True)),
                ('turf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turf_app.turftbl')),
            ],
        ),
    ]
