# Generated by Django 5.0.1 on 2024-02-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0019_turfreview_tbl_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfreview_tbl',
            name='turf_id',
        ),
        migrations.AddField(
            model_name='turfreview_tbl',
            name='tname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
