# Generated by Django 5.0.1 on 2024-02-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0020_remove_turfreview_tbl_turf_id_turfreview_tbl_tname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfreview_tbl',
            name='tname',
        ),
        migrations.AddField(
            model_name='turfreview_tbl',
            name='turf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turf_app.turftbl'),
        ),
    ]
