# Generated by Django 5.0.1 on 2024-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0021_remove_turfreview_tbl_tname_turfreview_tbl_turf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turftbl',
            name='amount',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
