# Generated by Django 5.0.1 on 2024-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0022_turftbl_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtbl',
            name='totalamt',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
