# Generated by Django 5.0.1 on 2024-02-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0023_bookingtbl_totalamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtbl',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingtbl',
            name='totalamt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='managertbl',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='turftbl',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertbl',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
