# Generated by Django 5.0.1 on 2024-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0024_alter_bookingtbl_contact_alter_bookingtbl_totalamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turftbl',
            name='grass',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='turftbl',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='turftbl',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
