# Generated by Django 5.0.1 on 2024-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0026_resources_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turftbl',
            old_name='services',
            new_name='sports',
        ),
        migrations.AddField(
            model_name='turftbl',
            name='res_number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='resources_tbl',
        ),
    ]
