# Generated by Django 5.0.1 on 2024-03-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0028_turftbl_res_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turftbl',
            name='res_name',
        ),
        migrations.RemoveField(
            model_name='turftbl',
            name='res_number',
        ),
        migrations.CreateModel(
            name='resource_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=10, null=True)),
                ('res_number', models.IntegerField(null=True)),
                ('turf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turf_app.turftbl')),
            ],
        ),
    ]
