# Generated by Django 5.0.1 on 2024-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0029_remove_turftbl_res_name_remove_turftbl_res_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_tbl',
            name='turf_id',
        ),
        migrations.AddField(
            model_name='resource_tbl',
            name='turf_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
