# Generated by Django 5.0.1 on 2024-03-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0030_remove_resource_tbl_turf_id_resource_tbl_turf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='turftbl',
            name='district',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
