# Generated by Django 5.0.1 on 2024-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0033_remove_bookingtbl_res_id_remove_bookingtbl_turf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtbl',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingtbl',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
