# Generated by Django 5.0.1 on 2024-03-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0034_bookingtbl_fname_bookingtbl_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtbl',
            name='phoneno',
        ),
    ]
