# Generated by Django 5.0.1 on 2024-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0035_remove_bookingtbl_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turftbl',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
