# Generated by Django 5.0.1 on 2024-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0037_reviewrating_tbl_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating_tbl',
            name='rating',
        ),
    ]
