# Generated by Django 5.0.1 on 2024-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0038_remove_reviewrating_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtbl',
            name='sports',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
